FROM node:22-alpine AS builder

WORKDIR /app
COPY frontend/package.json ./
RUN npm install
COPY frontend /app
RUN npm run build

FROM nginx:1.27-alpine

RUN apk add --no-cache gzip

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

# Enable gzip compression
RUN sed -i '/gzip on;/s/^/# /' /etc/nginx/nginx.conf
RUN echo 'gzip on; gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;' >> /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
